### ISSUE TITLE
GraphViz Installation issue on OS X

### ISSUE THREAD

**Issue by mlubin** [Keno/GraphViz.jl#13]
Reported by a user, Julia 0.3.4:

```
julia> Homebrew.rm("graphviz")

Uninstalling graphviz...



julia> Homebrew.add("graphviz")

==> Installing graphviz from staticfloat/homebrew-juliadeps

==> Downloading https://juliabottles.s3.amazonaws.com/graphviz-2.38.0.yosemite.b

Already downloaded: /Users/xxx/Library/Caches/Homebrew.jl/graphviz-2.38.0.yosemite.bottle.tar.gz

==> Pouring graphviz-2.38.0.yosemite.bottle.tar.gz

🍺  /Users/xxx/.julia/v0.3/Homebrew/deps/usr/Cellar/graphviz/2.38.0: 470 files, 68M

To relink: brew unlink graphviz && brew link graphviz



julia> INFO: Building GraphViz

       Unlinking /Users/xxx/.julia/v0.3/Homebrew/deps/usr/Cellar/graphviz/2.38.0... 99 symlinks removed

julia> INFO: Building GraphViz

       Unlinking /Users/xxx/.julia/v0.3/Homebrew/deps/usr/Cellar/graphviz/2.38.0... 99 symlinks removed

julia> Pkg.build("GraphViz")

INFO: Building GraphViz

Unlinking /Users/xxx/.julia/v0.3/Homebrew/deps/usr/Cellar/graphviz/2.38.0... 99 symlinks removed

Warning: graphviz-2.38.0 already installed, it's just not linked

Linking /Users/xxx/.julia/v0.3/Homebrew/deps/usr/Cellar/graphviz/2.38.0... 99 symlinks created

==============================[ ERROR: GraphViz ]===============================



Provider PackageManager failed to satisfy dependency gvc

while loading /Users/xxx/.julia/v0.3/GraphViz/deps/build.jl, in expression starting on line 42
```

@staticfloat, is there a typical cause for the "installed but not linked" issue?

**Comment by staticfloat** [comment]
That notice is normal. What does `BinDeps.debug("GraphViz")` say?

**Comment by mlubin** [comment]
A number of users have experienced this, here's a sample error:
```
julia> dlopen("/Users/tmak/.julia/v0.3/Homebrew/deps/usr/Cellar/graphviz/2.38.0/lib/libgvc")
ERROR: could not load module /Users/tmak/.julia/v0.3/Homebrew/deps/usr/Cellar/graphviz/2.38.0/lib/libgvc: dlopen(/Users/tmak/.julia/v0.3/Homebrew/deps/usr/Cellar/graphviz/2.38.0/lib/libgvc.dylib, 1): Library not loaded: /Users/tmak/.julia/v0.3/Homebrew/deps/usr/lib/libltdl.7.dylib
  Referenced from: /Users/tmak/.julia/v0.3/Homebrew/deps/usr/Cellar/graphviz/2.38.0/lib/libgvc.dylib
  Reason: image not found
 in dlopen at c.jl:19
```

There's no libltdl.7.dylib installed.

**Comment by mlubin** [comment]
@staticfloat, does libtool need to be added as a dependency of graphviz?

**Comment by staticfloat** [comment]
Oh bother.  This is probably one of those things where if libtool is present, it will link it in, but it doesn't declare it as an actual dependency.  I'll fix this.

**Comment by staticfloat** [comment]
New bottle up.  Want to tell the users to try these new bottles after a `Pkg.update()`?

**Comment by mlubin** [comment]
Working now, thanks!

There's now a warning about pango:
```
(process:13571): Pango-CRITICAL **: No modules found:
No builtin or dynamically loaded modules were found.
PangoFc will not work correctly.
This probably means there was an error in the creation of:
  '/usr/local/Cellar/pango/1.36.8/etc/pango/pango.modules'
You should create this file by running:
  pango-querymodules > '/usr/local/Cellar/pango/1.36.8/etc/pango/pango.modules'

(process:13571): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderCoreText', script='common'
```
Closing since unrelated to GraphViz.

**Comment by staticfloat** [comment]
Actually, I think this is still related to GraphViz.   Since this package uses pango, but doesn't call `using Cairo`, we need to duplicate [this initialization routine](https://github.com/JuliaLang/Cairo.jl/blob/master/deps/build.jl#L40-L42) here.

**Comment by foebu** [comment]
I still got the problem:
Warning: graphviz-2.38.0 already installed, it's just not linked

The strange thing is that on mavericks the stable version should be 2.36, while brew tries to install the 2.38.

**Comment by staticfloat** [comment]
Hey @foebu, that warning message is normal, don't worry about it.  Note that the version of `graphviz` that is getting installed is coming from [this homebrew tap](https://github.com/staticfloat/homebrew-juliadeps), which has 2.38 as the stable version.

**Comment by foebu** [comment]
Hi @staticfloat, apparently no. Even though I got some issues with pygraphviz library and python 3, due to the fact that the library couldn't locate graphviz. But I think that's not your problem, but their problem :)

**Comment by staticfloat** [comment]
Yep, you're going to have to point pygraphviz at the library somehow, perhaps with DYLD_FALLBACK_LIBRARY_PATH or some such, because its in a very non-standard location (inside your .julia directory). That's the best tip I can give you.
